version: "3.6"
services:
  # app:
  #   image: flask
  #   container_name: flask-app
  #   env_file: .env
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - private

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - private
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    networks:
      - private
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@email.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:

networks:
  private:
