apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
type: Opaque
data:
  OWM_API_KEY: d450b90dbe928b2c3f42735ddac9c6b8
  # OWM_API_KEY: <OWM_API_KEY>
  POSTGRES_DATABASE_URI: postgresql://postgres:postgres@postgres:5432/postgres
  # POSTGRES_DATABASE_URI: <POSTGRES_DATABASE_URI>
