---
defaultRules:
  rules:
    etcd: false
    kubeScheduler: false
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
prometheus:
  prometheusSpec:
    serviceMonitorSelector:
      matchLabels:
        prometheus: devops
    additionalScrapeConfigs:
      - job_name: "postgres-exporter"
        static_configs:
          - targets:
              - pg-exporter-service.default.svc.cluster.local:9187
      - job_name: "flask-exporter"
        static_configs:
          - targets:
              - flask-service.default.svc.cluster.local:8080
commonLabels:
  prometheus: devops
grafana:
  adminPassword: <GRAFANA_PASSWORD>
